# Generated by Django 4.2.7 on 2023-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('release_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=True, max_digits=10000000)),
                ('perfil', models.ImageField(null=True, upload_to='perfil/', verbose_name='Perfil')),
            ],
        ),
    ]
